import pandas as pd
#converter países para inglês

#criar um dataframe manipulável
dataframe = pd.read_csv('data_base.csv', sep=',')

#pegar o dicionário de traduções
converter_dict = {
    'Afeganistão': 'Afghanistan',
    'África do Sul': 'South Africa',
    'Albânia': 'Albania',
    'Alemanha': 'Germany',
    'Andorra': 'Andorra',
    'Angola': 'Angola',
    'Antígua e Barbuda': 'Antigua and Barbuda',
    'Arábia Saudita': 'Saudi Arabia',
    'Argélia': 'Algeria',
    'Argentina': 'Argentina',
    'Armênia': 'Armenia',
    'Austrália': 'Australia',
    'Áustria': 'Austria',
    'Azerbaijão': 'Azerbaijan',
    'Bahamas': 'Bahamas, The',
    'Bahrein': 'Bahrain',
    'Bangladesh': 'Bangladesh',
    'Barbados': 'Barbados',
    'Belarus': 'Belarus',
    'Bélgica': 'Belgium',
    'Belize': 'Belize',
    'Benin': 'Benin',
    'Butão': 'Bhutan',
    'Bolívia': 'Bolivia',
    'Bósnia e Herzegovina': 'Bosnia and Herzegovina',
    'Botsuana': 'Botswana',
    'Brasil': 'Brazil',
    'Brunei': 'Brunei Darussalam',
    'Bulgária': 'Bulgaria',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Cabo Verde': 'Cabo Verde',
    'Camboja': 'Cambodia',
    'Camarões': 'Cameroon',
    'Canadá': 'Canada',
    'Catar': 'Qatar',
    'Cazaquistão': 'Kazakhstan',
    'Chade': 'Chad',
    'Chile': 'Chile',
    'China': 'China',
    'Chipre': 'Cyprus',
    'Colômbia': 'Colombia',
    'Comores': 'Comoros',
    'Congo': 'Congo, Rep.',
    'Coreia do Norte': "Korea, Dem. People's Rep.",
    'Coreia do Sul': 'Korea, Rep.',
    'Costa do Marfim': "Cote d'Ivoire",
    'Costa Rica': 'Costa Rica',
    'Croácia': 'Croatia',
    'Cuba': 'Cuba',
    'Dinamarca': 'Denmark',
    'Djibuti': 'Djibouti',
    'Dominica': 'Dominica',
    'Egito': 'Egypt, Arab Rep.',
    'El Salvador': 'El Salvador',
    'Emirados Árabes Unidos': 'United Arab Emirates',
    'Equador': 'Ecuador',
    'Eritreia': 'Eritrea',
    'Eslováquia': 'Slovak Republic',
    'Eslovênia': 'Slovenia',
    'Espanha': 'Spain',
    'Essuatíni': 'Eswatini',
    'Estados Unidos': 'United States',
    'Estônia': 'Estonia',
    'Etiópia': 'Ethiopia',
    'Fiji': 'Fiji',
    'Filipinas': 'Philippines',
    'Finlândia': 'Finland',
    'França': 'France',
    'Gabão': 'Gabon',
    'Gâmbia': 'Gambia, The',
    'Gana': 'Ghana',
    'Geórgia': 'Georgia',
    'Granada': 'Grenada',
    'Grécia': 'Greece',
    'Guatemala': 'Guatemala',
    'Guiana': 'Guyana',
    'Guiné': 'Guinea',
    'Guiné-Bissau': 'Guinea-Bissau',
    'Guiné Equatorial': 'Equatorial Guinea',
    'Haiti': 'Haiti',
    'Honduras': 'Honduras',
    'Hungria': 'Hungary',
    'Iêmen': 'Yemen, Rep.',
    'Ilhas Marshall': 'Marshall Islands',
    'Índia': 'India',
    'Indonésia': 'Indonesia',
    'Irã': 'Iran, Islamic Rep.',
    'Iraque': 'Iraq',
    'Irlanda': 'Ireland',
    'Islândia': 'Iceland',
    'Israel': 'Israel',
    'Itália': 'Italy',
    'Jamaica': 'Jamaica',
    'Japão': 'Japan',
    'Jordânia': 'Jordan',
    'Kiribati': 'Kiribati',
    'Kuwait': 'Kuwait',
    'Laos': 'Lao PDR',
    'Lesoto': 'Lesotho',
    'Letônia': 'Latvia',
    'Líbano': 'Lebanon',
    'Libéria': 'Liberia',
    'Líbia': 'Libya',
    'Liechtenstein': 'Liechtenstein',
    'Lituânia': 'Lithuania',
    'Luxemburgo': 'Luxembourg',
    'Macedônia do Norte': 'North Macedonia',
    'Madagascar': 'Madagascar',
    'Malásia': 'Malaysia',
    'Malawi': 'Malawi',
    'Maldivas': 'Maldives',
    'Mali': 'Mali',
    'Malta': 'Malta',
    'Marrocos': 'Morocco',
    'Maurício': 'Mauritius',
    'Mauritânia': 'Mauritania',
    'México': 'Mexico',
    'Micronésia': 'Micronesia, Fed. Sts.',
    'Moçambique': 'Mozambique',
    'Moldávia': 'Moldova',
    'Mônaco': 'Monaco',
    'Mongólia': 'Mongolia',
    'Montenegro': 'Montenegro',
    'Myanmar': 'Myanmar',
    'Namíbia': 'Namibia',
    'Nauru': 'Nauru',
    'Nepal': 'Nepal',
    'Nicarágua': 'Nicaragua',
    'Níger': 'Niger',
    'Nigéria': 'Nigeria',
    'Noruega': 'Norway',
    'Nova Zelândia': 'New Zealand',
    'Omã': 'Oman',
    'Países Baixos': 'Netherlands',
    'Palau': 'Palau',
    'Panamá': 'Panama',
    'Papua-Nova Guiné': 'Papua New Guinea',
    'Paquistão': 'Pakistan',
    'Paraguai': 'Paraguay',
    'Peru': 'Peru',
    'Polônia': 'Poland',
    'Portugal': 'Portugal',
    'Quênia': 'Kenya',
    'Quirguistão': 'Kyrgyz Republic',
    'Reino Unido': 'United Kingdom',
    'República Centro-Africana': 'Central African Republic',
    'República Democrática do Congo': 'Congo, Dem. Rep.',
    'República Dominicana': 'Dominican Republic',
    'República Tcheca': 'Czechia',
    'Romênia': 'Romania',
    'Ruanda': 'Rwanda',
    'Rússia': 'Russian Federation',
    'Samoa': 'Samoa',
    'San Marino': 'San Marino',
    'Santa Lúcia': 'St. Lucia',
    'São Cristóvão e Névis': 'St. Kitts and Nevis',
    'São Tomé e Príncipe': 'Sao Tome and Principe',
    'São Vicente e Granadinas': 'St. Vincent and the Grenadines',
    'Seicheles': 'Seychelles',
    'Senegal': 'Senegal',
    'Serra Leoa': 'Sierra Leone',
    'Sérvia': 'Serbia',
    'Singapura': 'Singapore',
    'Síria': 'Syrian Arab Republic',
    'Somália': 'Somalia',
    'Sri Lanka': 'Sri Lanka',
    'Sudão': 'Sudan',
    'Sudão do Sul': 'South Sudan',
    'Suécia': 'Sweden',
    'Suíça': 'Switzerland',
    'Suriname': 'Suriname',
    'Tailândia': 'Thailand',
    'Tajiquistão': 'Tajikistan',
    'Tanzânia': 'Tanzania',
    'Timor-Leste': 'Timor-Leste',
    'Togo': 'Togo',
    'Tonga': 'Tonga',
    'Trinidad e Tobago': 'Trinidad and Tobago',
    'Tunísia': 'Tunisia',
    'Turcomenistão': 'Turkmenistan',
    'Turquia': 'Turkiye',
    'Tuvalu': 'Tuvalu',
    'Ucrânia': 'Ukraine',
    'Uganda': 'Uganda',
    'Uruguai': 'Uruguay',
    'Uzbequistão': 'Uzbekistan',
    'Vanuatu': 'Vanuatu',
    'Vaticano': 'Vatican City',
    'Venezuela': 'Venezuela, RB',
    'Vietnã': 'Viet Nam',
    'Zâmbia': 'Zambia',
    'Zimbábue': 'Zimbabwe'
}


#função que pega o valor de cada chave, retornando o país em inglês
def country_converter(name:str) -> str:
  if name in converter_dict:
    return converter_dict[name]
  
#apply aplica tudo aos dados da coluna countries
dataframe['countries'] = dataframe['countries'].apply(country_converter)

#juntar ordem alfabética, por padrão ascending é verdadeiro
dataframe = dataframe.sort_values(['countries', 'year'])

#criamos o novo csv
dataframe.to_csv('data_frame_en.csv', index=False)

