import pandas as pd
#converter países para inglês

#criar um dataframe manipulável
dataframe = pd.read_csv('data_base.csv', sep=',')
hdi_df = pd.read_json('data/HDI/hdr-data.json')
imf_data = pd.read_csv('data/development-revenue/world-imf2026.csv')

imf_to_df_dict = {
    'Afghanistan': 'Afghanistan',
    'Albania': 'Albania',
    'Algeria': 'Algeria',
    'Andorra': 'Andorra',
    'Angola': 'Angola',
    'Antigua and Barbuda': 'Antigua and Barbuda',
    'Argentina': 'Argentina',
    'Armenia': 'Armenia',
    'Australia': 'Australia',
    'Austria': 'Austria',
    'Azerbaijan': 'Azerbaijan',
    'Bahrain': 'Bahrain',
    'Bangladesh': 'Bangladesh',
    'Barbados': 'Barbados',
    'Belarus': 'Belarus',
    'Belgium': 'Belgium',
    'Belize': 'Belize',
    'Benin': 'Benin',
    'Bhutan': 'Bhutan',
    'Bolivia': 'Bolivia',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'Botswana': 'Botswana',
    'Brazil': 'Brazil',
    'Brunei Darussalam': 'Brunei Darussalam',
    'Bulgaria': 'Bulgaria',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Cabo Verde': 'Cabo Verde',
    'Cambodia': 'Cambodia',
    'Cameroon': 'Cameroon',
    'Canada': 'Canada',
    'Central African Republic': 'Central African Republic',
    'Chad': 'Chad',
    'Chile': 'Chile',
    'China': 'China',
    'Colombia': 'Colombia',
    'Comoros': 'Comoros',
    'Congo, Dem. Rep.': 'Congo, Dem. Rep.',
    'Congo, Rep.': 'Congo, Rep.',
    'Costa Rica': 'Costa Rica',
    "Cote d'Ivoire": "Cote d'Ivoire",
    'Croatia': 'Croatia',
    'Cuba': 'Cuba',
    'Cyprus': 'Cyprus',
    'Czech Republic': 'Czechia',
    'Democratic Republic of the Congo': 'Congo, Dem. Rep.',
    'Denmark': 'Denmark',
    'Djibouti': 'Djibouti',
    'Dominica': 'Dominica',
    'Dominican Republic': 'Dominican Republic',
    'Ecuador': 'Ecuador',
    'Egypt': 'Egypt, Arab Rep.',
    'El Salvador': 'El Salvador',
    'Equatorial Guinea': 'Equatorial Guinea',
    'Eritrea': 'Eritrea',
    'Estonia': 'Estonia',
    'Eswatini': 'Eswatini',
    'Ethiopia': 'Ethiopia',
    'Fiji': 'Fiji',
    'Finland': 'Finland',
    'France': 'France',
    'Gabon': 'Gabon',
    'Georgia': 'Georgia',
    'Germany': 'Germany',
    'Ghana': 'Ghana',
    'Greece': 'Greece',
    'Grenada': 'Grenada',
    'Guatemala': 'Guatemala',
    'Guinea': 'Guinea',
    'Guinea-Bissau': 'Guinea-Bissau',
    'Guyana': 'Guyana',
    'Haiti': 'Haiti',
    'Honduras': 'Honduras',
    'Hungary': 'Hungary',
    'Iceland': 'Iceland',
    'India': 'India',
    'Indonesia': 'Indonesia',
    'Iran': 'Iran, Islamic Rep.',
    'Iraq': 'Iraq',
    'Ireland': 'Ireland',
    'Israel': 'Israel',
    'Italy': 'Italy',
    'Jamaica': 'Jamaica',
    'Japan': 'Japan',
    'Jordan': 'Jordan',
    'Kazakhstan': 'Kazakhstan',
    'Kenya': 'Kenya',
    'Kiribati': 'Kiribati',
    'Korea': 'Korea, Rep.',
    'Kuwait': 'Kuwait',
    'Kyrgyz Republic': 'Kyrgyz Republic',
    'Lao P.D.R': 'Lao PDR',
    'Latvia': 'Latvia',
    'Lebanon': 'Lebanon',
    'Lesotho': 'Lesotho',
    'Liberia': 'Liberia',
    'Libya': 'Libya',
    'Lithuania': 'Lithuania',
    'Luxembourg': 'Luxembourg',
    'Madagascar': 'Madagascar',
    'Malawi': 'Malawi',
    'Malaysia': 'Malaysia',
    'Maldives': 'Maldives',
    'Mali': 'Mali',
    'Malta': 'Malta',
    'Marshall Islands': 'Marshall Islands',
    'Mauritania': 'Mauritania',
    'Mauritius': 'Mauritius',
    'Mexico': 'Mexico',
    'Micronesia': 'Micronesia, Fed. Sts.',
    'Moldova': 'Moldova',
    'Monaco': 'Monaco',
    'Mongolia': 'Mongolia',
    'Montenegro': 'Montenegro',
    'Morocco': 'Morocco',
    'Mozambique': 'Mozambique',
    'Myanmar': 'Myanmar',
    'Namibia': 'Namibia',
    'Nauru': 'Nauru',
    'Nepal': 'Nepal',
    'Netherlands': 'Netherlands',
    'New Zealand': 'New Zealand',
    'Nicaragua': 'Nicaragua',
    'Niger': 'Niger',
    'Nigeria': 'Nigeria',
    'North Macedonia': 'North Macedonia',
    'Norway': 'Norway',
    'Oman': 'Oman',
    'Pakistan': 'Pakistan',
    'Palau': 'Palau',
    'Panama': 'Panama',
    'Papua New Guinea': 'Papua New Guinea',
    'Paraguay': 'Paraguay',
    'Peru': 'Peru',
    'Philippines': 'Philippines',
    'Poland': 'Poland',
    'Portugal': 'Portugal',
    'Qatar': 'Qatar',
    'Republic of Congo': 'Congo, Rep.',
    'Romania': 'Romania',
    'Russia': 'Russian Federation',
    'Rwanda': 'Rwanda',
    'Samoa': 'Samoa',
    'San Marino': 'San Marino',
    'Sao Tome and Principe': 'Sao Tome and Principe',
    'Saudi Arabia': 'Saudi Arabia',
    'Senegal': 'Senegal',
    'Serbia': 'Serbia',
    'Seychelles': 'Seychelles',
    'Sierra Leone': 'Sierra Leone',
    'Singapore': 'Singapore',
    'Slovak Republic': 'Slovak Republic',
    'Slovenia': 'Slovenia',
    'Somalia': 'Somalia',
    'South Africa': 'South Africa',
    'South Sudan': 'South Sudan',
    'Spain': 'Spain',
    'Sri Lanka': 'Sri Lanka',
    'St. Kitts and Nevis': 'St. Kitts and Nevis',
    'St. Lucia': 'St. Lucia',
    'St. Vincent and the Grenadines': 'St. Vincent and the Grenadines',
    'Sudan': 'Sudan',
    'Suriname': 'Suriname',
    'Sweden': 'Sweden',
    'Switzerland': 'Switzerland',
    'Syrian Arab Republic': 'Syrian Arab Republic',
    'Tajikistan': 'Tajikistan',
    'Tanzania': 'Tanzania',
    'Thailand': 'Thailand',
    'The Bahamas': 'Bahamas, The',
    'The Gambia': 'Gambia, The',
    'Timor-Leste': 'Timor-Leste',
    'Togo': 'Togo',
    'Tonga': 'Tonga',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'Tunisia': 'Tunisia',
    'Turkmenistan': 'Turkmenistan',
    'Tuvalu': 'Tuvalu',
    'Türkiye': 'Turkiye',
    'UAE': 'United Arab Emirates',
    'Uganda': 'Uganda',
    'Ukraine': 'Ukraine',
    'United Kingdom': 'United Kingdom',
    'United States': 'United States',
    'Uruguay': 'Uruguay',
    'Uzbekistan': 'Uzbekistan',
    'Vanuatu': 'Vanuatu',
    'Venezuela': 'Venezuela, RB',
    'Vietnam': 'Viet Nam',
    'Yemen': 'Yemen, Rep.',
    'Zambia': 'Zambia',
    'Zimbabwe': 'Zimbabwe',
}

converter_dict_hdi = {
    'Afghanistan': 'Afghanistan',
    'Angola': 'Angola',
    'Albania': 'Albania',
    'Andorra': 'Andorra',
    'United Arab Emirates': 'United Arab Emirates',
    'Argentina': 'Argentina',
    'Armenia': 'Armenia',
    'Australia': 'Australia',
    'Austria': 'Austria',
    'Azerbaijan': 'Azerbaijan',
    'Burundi': 'Burundi',
    'Belgium': 'Belgium',
    'Benin': 'Benin',
    'Burkina Faso': 'Burkina Faso',
    'Bangladesh': 'Bangladesh',
    'Bulgaria': 'Bulgaria',
    'Bahrain': 'Bahrain',
    'Bahamas': 'Bahamas, The',  # DIFERENTE: test_idea tem 'Bahamas', data_frame_en tem 'Bahamas, The'
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'Belarus': 'Belarus',
    'Belize': 'Belize',
    'Bolivia (Plurinational State of)': 'Bolivia',  # DIFERENTE: test_idea tem o nome completo
    'Brazil': 'Brazil',
    'Barbados': 'Barbados',
    'Brunei Darussalam': 'Brunei Darussalam',
    'Bhutan': 'Bhutan',
    'Botswana': 'Botswana',
    'Central African Republic': 'Central African Republic',
    'Canada': 'Canada',
    'Switzerland': 'Switzerland',
    'Chile': 'Chile',
    'China': 'China',
    "Côte d'Ivoire": 'Cote d\'Ivoire',  # DIFERENTE: acento vs sem acento
    'Cameroon': 'Cameroon',
    'Congo (Democratic Republic of the)': 'Congo, Dem. Rep.',  # DIFERENTE: nome completo vs abreviado
    'Congo': 'Congo, Rep.',  # DIFERENTE: 'Congo' vs 'Congo, Rep.'
    'Colombia': 'Colombia',
    'Comoros': 'Comoros',
    'Cabo Verde': 'Cabo Verde',
    'Costa Rica': 'Costa Rica',
    'Cuba': 'Cuba',
    'Cyprus': 'Cyprus',
    'Czechia': 'Czechia',
    'Germany': 'Germany',
    'Djibouti': 'Djibouti',
    'Dominica': 'Dominica',
    'Denmark': 'Denmark',
    'Dominican Republic': 'Dominican Republic',
    'Algeria': 'Algeria',
    'Ecuador': 'Ecuador',
    'Egypt': 'Egypt, Arab Rep.',  # DIFERENTE: 'Egypt' vs 'Egypt, Arab Rep.'
    'Eritrea': 'Eritrea',
    'Spain': 'Spain',
    'Estonia': 'Estonia',
    'Ethiopia': 'Ethiopia',
    'Finland': 'Finland',
    'Fiji': 'Fiji',
    'France': 'France',
    'Micronesia (Federated States of)': 'Micronesia, Fed. Sts.',  # DIFERENTE
    'Gabon': 'Gabon',
    'United Kingdom': 'United Kingdom',
    'Georgia': 'Georgia',
    'Ghana': 'Ghana',
    'Guinea': 'Guinea',
    'Gambia': 'Gambia, The',  # DIFERENTE: 'Gambia' vs 'Gambia, The'
    'Guinea-Bissau': 'Guinea-Bissau',
    'Equatorial Guinea': 'Equatorial Guinea',
    'Greece': 'Greece',
    'Grenada': 'Grenada',
    'Guatemala': 'Guatemala',
    'Guyana': 'Guyana',
    "Hong Kong, China (SAR)": "Hong Kong, China (SAR)",
    'Honduras': 'Honduras',
    'Croatia': 'Croatia',
    'Haiti': 'Haiti',
    'Hungary': 'Hungary',
    'Indonesia': 'Indonesia',
    'India': 'India',
    'Ireland': 'Ireland',
    'Iran (Islamic Republic of)': 'Iran, Islamic Rep.',  # DIFERENTE
    'Iraq': 'Iraq',
    'Iceland': 'Iceland',
    'Israel': 'Israel',
    'Italy': 'Italy',
    'Jamaica': 'Jamaica',
    'Jordan': 'Jordan',
    'Japan': 'Japan',
    'Kazakhstan': 'Kazakhstan',
    'Kenya': 'Kenya',
    'Kyrgyzstan': 'Kyrgyz Republic',  # DIFERENTE
    'Cambodia': 'Cambodia',
    'Kiribati': 'Kiribati',
    'Saint Kitts and Nevis': 'St. Kitts and Nevis',  # DIFERENTE
    'Korea (Republic of)': 'Korea, Rep.',  # DIFERENTE
    'Kuwait': 'Kuwait',
    'Lao People\'s Democratic Republic': 'Lao PDR',  # DIFERENTE
    'Lebanon': 'Lebanon',
    'Liberia': 'Liberia',
    'Libya': 'Libya',
    'Saint Lucia': 'St. Lucia',  # DIFERENTE
    'Liechtenstein': 'Liechtenstein',
    'Sri Lanka': 'Sri Lanka',
    'Lesotho': 'Lesotho',
    'Lithuania': 'Lithuania',
    'Luxembourg': 'Luxembourg',
    'Latvia': 'Latvia',
    'Morocco': 'Morocco',
    'Monaco': 'Monaco',
    'Moldova (Republic of)': 'Moldova',  # DIFERENTE
    'Madagascar': 'Madagascar',
    'Maldives': 'Maldives',
    'Mexico': 'Mexico',
    'Marshall Islands': 'Marshall Islands',
    'North Macedonia': 'North Macedonia',
    'Mali': 'Mali',
    'Malta': 'Malta',
    'Myanmar': 'Myanmar',
    'Montenegro': 'Montenegro',
    'Mongolia': 'Mongolia',
    'Mozambique': 'Mozambique',
    'Mauritania': 'Mauritania',
    'Mauritius': 'Mauritius',
    'Malawi': 'Malawi',
    'Malaysia': 'Malaysia',
    'Namibia': 'Namibia',
    'Niger': 'Niger',
    'Nigeria': 'Nigeria',
    'Nicaragua': 'Nicaragua',
    'Netherlands': 'Netherlands',
    'Norway': 'Norway',
    'Nepal': 'Nepal',
    'Nauru': 'Nauru',
    'New Zealand': 'New Zealand',
    'Oman': 'Oman',
    'Pakistan': 'Pakistan',
    'Panama': 'Panama',
    'Peru': 'Peru',
    'Philippines': 'Philippines',
    'Palau': 'Palau',
    'Papua New Guinea': 'Papua New Guinea',
    'Poland': 'Poland',
    "Korea (Democratic People's Rep. of)": "Korea, Dem. People's Rep.",  # DIFERENTE
    'Portugal': 'Portugal',
    'Paraguay': 'Paraguay',
    "Palestine, State of": "Palestine, State of",
    'Qatar': 'Qatar',
    'Romania': 'Romania',
    'Russian Federation': 'Russian Federation',
    'Rwanda': 'Rwanda',
    'Saudi Arabia': 'Saudi Arabia',
    'Sudan': 'Sudan',
    'Senegal': 'Senegal',
    'Singapore': 'Singapore',
    'Solomon Islands': 'Solomon Islands',
    'Sierra Leone': 'Sierra Leone',
    'El Salvador': 'El Salvador',
    'San Marino': 'San Marino',
    'Somalia': 'Somalia',
    'Serbia': 'Serbia',
    'South Sudan': 'South Sudan',
    'Sao Tome and Principe': 'Sao Tome and Principe',
    'Suriname': 'Suriname',
    'Slovakia': 'Slovak Republic',  # DIFERENTE
    'Slovenia': 'Slovenia',
    'Sweden': 'Sweden',
    'Eswatini (Kingdom of)': 'Eswatini',  # DIFERENTE
    'Seychelles': 'Seychelles',
    'Syrian Arab Republic': 'Syrian Arab Republic',
    'Chad': 'Chad',
    'Togo': 'Togo',
    'Thailand': 'Thailand',
    'Tajikistan': 'Tajikistan',
    'Turkmenistan': 'Turkmenistan',
    'Timor-Leste': 'Timor-Leste',
    'Tonga': 'Tonga',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'Tunisia': 'Tunisia',
    'Türkiye': 'Turkiye',  # DIFERENTE: com ü vs sem ü
    'Tuvalu': 'Tuvalu',
    'Tanzania (United Republic of)': 'Tanzania',  # DIFERENTE
    'Uganda': 'Uganda',
    'Ukraine': 'Ukraine',
    'Uruguay': 'Uruguay',
    'United States': 'United States',
    'Uzbekistan': 'Uzbekistan',
    'Saint Vincent and the Grenadines': 'St. Vincent and the Grenadines',  # DIFERENTE
    'Venezuela (Bolivarian Republic of)': 'Venezuela, RB',  # DIFERENTE
    'Viet Nam': 'Viet Nam',
    'Vanuatu': 'Vanuatu',
    'Samoa': 'Samoa',
    'Yemen': 'Yemen, Rep.',  # DIFERENTE: 'Yemen' vs 'Yemen, Rep.'
    'South Africa': 'South Africa',
    'Zambia': 'Zambia',
    'Zimbabwe': 'Zimbabwe'
}


#pegar o dicionário de traduções
converter_dict_general = {
    'Afeganistão': 'Afghanistan',
    'África do Sul': 'South Africa',
    'Albânia': 'Albania',
    'Alemanha': 'Germany',
    'Andorra': 'Andorra',
    'Angola': 'Angola',
    'Antígua e Barbuda': 'Antigua and Barbuda',
    'Arábia Saudita': 'Saudi Arabia',
    'Argélia': 'Algeria',
    'Argentina': 'Argentina',
    'Armênia': 'Armenia',
    'Austrália': 'Australia',
    'Áustria': 'Austria',
    'Azerbaijão': 'Azerbaijan',
    'Bahamas': 'Bahamas, The',
    'Bahrein': 'Bahrain',
    'Bangladesh': 'Bangladesh',
    'Barbados': 'Barbados',
    'Belarus': 'Belarus',
    'Bélgica': 'Belgium',
    'Belize': 'Belize',
    'Benin': 'Benin',
    'Butão': 'Bhutan',
    'Bolívia': 'Bolivia',
    'Bósnia e Herzegovina': 'Bosnia and Herzegovina',
    'Botsuana': 'Botswana',
    'Brasil': 'Brazil',
    'Brunei': 'Brunei Darussalam',
    'Bulgária': 'Bulgaria',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Cabo Verde': 'Cabo Verde',
    'Camboja': 'Cambodia',
    'Camarões': 'Cameroon',
    'Canadá': 'Canada',
    'Catar': 'Qatar',
    'Cazaquistão': 'Kazakhstan',
    'Chade': 'Chad',
    'Chile': 'Chile',
    'China': 'China',
    'Chipre': 'Cyprus',
    'Colômbia': 'Colombia',
    'Comores': 'Comoros',
    'Congo': 'Congo, Rep.',
    'Coreia do Norte': "Korea, Dem. People's Rep.",
    'Coreia do Sul': 'Korea, Rep.',
    'Costa do Marfim': "Cote d'Ivoire",
    'Costa Rica': 'Costa Rica',
    'Croácia': 'Croatia',
    'Cuba': 'Cuba',
    'Dinamarca': 'Denmark',
    'Djibuti': 'Djibouti',
    'Dominica': 'Dominica',
    'Egito': 'Egypt, Arab Rep.',
    'El Salvador': 'El Salvador',
    'Emirados Árabes Unidos': 'United Arab Emirates',
    'Equador': 'Ecuador',
    'Eritreia': 'Eritrea',
    'Eslováquia': 'Slovak Republic',
    'Eslovênia': 'Slovenia',
    'Espanha': 'Spain',
    'Essuatíni': 'Eswatini',
    'Estados Unidos': 'United States',
    'Estônia': 'Estonia',
    'Etiópia': 'Ethiopia',
    'Fiji': 'Fiji',
    'Filipinas': 'Philippines',
    'Finlândia': 'Finland',
    'França': 'France',
    'Gabão': 'Gabon',
    'Gâmbia': 'Gambia, The',
    'Gana': 'Ghana',
    'Geórgia': 'Georgia',
    'Granada': 'Grenada',
    'Grécia': 'Greece',
    'Guatemala': 'Guatemala',
    'Guiana': 'Guyana',
    'Guiné': 'Guinea',
    'Guiné-Bissau': 'Guinea-Bissau',
    'Guiné Equatorial': 'Equatorial Guinea',
    'Haiti': 'Haiti',
    'Honduras': 'Honduras',
    'Hungria': 'Hungary',
    'Iêmen': 'Yemen, Rep.',
    'Ilhas Marshall': 'Marshall Islands',
    'Índia': 'India',
    'Indonésia': 'Indonesia',
    'Irã': 'Iran, Islamic Rep.',
    'Iraque': 'Iraq',
    'Irlanda': 'Ireland',
    'Islândia': 'Iceland',
    'Israel': 'Israel',
    'Itália': 'Italy',
    'Jamaica': 'Jamaica',
    'Japão': 'Japan',
    'Jordânia': 'Jordan',
    'Kiribati': 'Kiribati',
    'Kuwait': 'Kuwait',
    'Laos': 'Lao PDR',
    'Lesoto': 'Lesotho',
    'Letônia': 'Latvia',
    'Líbano': 'Lebanon',
    'Libéria': 'Liberia',
    'Líbia': 'Libya',
    'Liechtenstein': 'Liechtenstein',
    'Lituânia': 'Lithuania',
    'Luxemburgo': 'Luxembourg',
    'Macedônia do Norte': 'North Macedonia',
    'Madagascar': 'Madagascar',
    'Malásia': 'Malaysia',
    'Malawi': 'Malawi',
    'Maldivas': 'Maldives',
    'Mali': 'Mali',
    'Malta': 'Malta',
    'Marrocos': 'Morocco',
    'Maurício': 'Mauritius',
    'Mauritânia': 'Mauritania',
    'México': 'Mexico',
    'Micronésia': 'Micronesia, Fed. Sts.',
    'Moçambique': 'Mozambique',
    'Moldávia': 'Moldova',
    'Mônaco': 'Monaco',
    'Mongólia': 'Mongolia',
    'Montenegro': 'Montenegro',
    'Myanmar': 'Myanmar',
    'Namíbia': 'Namibia',
    'Nauru': 'Nauru',
    'Nepal': 'Nepal',
    'Nicarágua': 'Nicaragua',
    'Níger': 'Niger',
    'Nigéria': 'Nigeria',
    'Noruega': 'Norway',
    'Nova Zelândia': 'New Zealand',
    'Omã': 'Oman',
    'Países Baixos': 'Netherlands',
    'Palau': 'Palau',
    'Panamá': 'Panama',
    'Papua-Nova Guiné': 'Papua New Guinea',
    'Paquistão': 'Pakistan',
    'Paraguai': 'Paraguay',
    'Peru': 'Peru',
    'Polônia': 'Poland',
    'Portugal': 'Portugal',
    'Quênia': 'Kenya',
    'Quirguistão': 'Kyrgyz Republic',
    'Reino Unido': 'United Kingdom',
    'República Centro-Africana': 'Central African Republic',
    'República Democrática do Congo': 'Congo, Dem. Rep.',
    'República Dominicana': 'Dominican Republic',
    'República Tcheca': 'Czechia',
    'Romênia': 'Romania',
    'Ruanda': 'Rwanda',
    'Rússia': 'Russian Federation',
    'Samoa': 'Samoa',
    'San Marino': 'San Marino',
    'Santa Lúcia': 'St. Lucia',
    'São Cristóvão e Névis': 'St. Kitts and Nevis',
    'São Tomé e Príncipe': 'Sao Tome and Principe',
    'São Vicente e Granadinas': 'St. Vincent and the Grenadines',
    'Seicheles': 'Seychelles',
    'Senegal': 'Senegal',
    'Serra Leoa': 'Sierra Leone',
    'Sérvia': 'Serbia',
    'Singapura': 'Singapore',
    'Síria': 'Syrian Arab Republic',
    'Somália': 'Somalia',
    'Sri Lanka': 'Sri Lanka',
    'Sudão': 'Sudan',
    'Sudão do Sul': 'South Sudan',
    'Suécia': 'Sweden',
    'Suíça': 'Switzerland',
    'Suriname': 'Suriname',
    'Tailândia': 'Thailand',
    'Tajiquistão': 'Tajikistan',
    'Tanzânia': 'Tanzania',
    'Timor-Leste': 'Timor-Leste',
    'Togo': 'Togo',
    'Tonga': 'Tonga',
    'Trinidad e Tobago': 'Trinidad and Tobago',
    'Tunísia': 'Tunisia',
    'Turcomenistão': 'Turkmenistan',
    'Turquia': 'Turkiye',
    'Tuvalu': 'Tuvalu',
    'Ucrânia': 'Ukraine',
    'Uganda': 'Uganda',
    'Uruguai': 'Uruguay',
    'Uzbequistão': 'Uzbekistan',
    'Vanuatu': 'Vanuatu',
    'Vaticano': 'Vatican City',
    'Venezuela': 'Venezuela, RB',
    'Vietnã': 'Viet Nam',
    'Zâmbia': 'Zambia',
    'Zimbábue': 'Zimbabwe'
}


#função que pega o valor de cada chave, retornando o país em inglês
def country_converter(name:str, converter_dict:dict) -> str:
  if name in converter_dict:
    return converter_dict[name]
  
#apply aplica tudo aos dados da coluna countries
dataframe['countries'] = dataframe['countries'].apply(country_converter, args=(converter_dict_general,))

#juntar ordem alfabética, por padrão ascending é verdadeiro
dataframe = dataframe.sort_values(['countries', 'year'])

#criamos o novo csv
dataframe.to_csv('data_frame_en.csv', index=False)

hdi_df['country'] = hdi_df['country'].apply(country_converter, args=(converter_dict_hdi,))

hdi_df = hdi_df.sort_values(['country', 'year'])

hdi_df.to_csv('data/HDI/hdr_data.csv')


imf_data['country'] = imf_data['country'].apply(country_converter,args=(imf_to_df_dict, ))

imf_data = imf_data.sort_values(['country', 'year'])

imf_data.to_csv('data/development-revenue/world-imf2026.csv')




